apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: siibra-spatial-backend
spec:
  commonName: siibra-spatial-backend.apps.tc.humanbrainproject.eu
  isCA: false
  dnsNames:
  - siibra-spatial-backend.apps.tc.humanbrainproject.eu
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production-issuer-1
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 120h
  secretName: siibra-spatial-backend-secret
  usages:
  - server auth
