repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: trailing-whitespace

-   repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    -   id: flake8
        additional_dependencies: [pep8-naming]

default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
