ARG BASE_IMAGE=docker-registry.ebrains.eu/hbp-spatial-backend/server:base-imgbuild

FROM ${BASE_IMAGE}

# to deal with non-ASCII characters in source
ENV LANG=C.UTF-8

ENV PATH=/usr/local/.pixi/envs/default/bin:$PATH

# Upgrade pip as recommended
RUN python -m ensurepip

# Setuptools is needed to import from source, wheel to build/install the
# package
RUN python -m pip install --no-cache-dir setuptools wheel
RUN python -m pip install --no-cache-dir gunicorn[gevent]

COPY . /source
RUN python -m pip install --no-cache-dir /source

ENV INSTANCE_PATH=/instance

VOLUME ${INSTANCE_PATH}

RUN useradd --create-home user
# RUN mkdir -p ${INSTANCE_PATH} && chown user:user ${INSTANCE_PATH}
USER user

ENV FLASK_APP=hbp_spatial_backend
EXPOSE 8080

ENTRYPOINT ["gunicorn"]

CMD ["--access-logfile=-", "--preload", "hbp_spatial_backend.wsgi:application", "--bind=:8080", "--worker-class=gevent"]
