apiVersion: v1
data:
  config.py: |
    CORS_ORIGINS = '*'
    PROXY_FIX = {
        'x_for': 1,
        'x_host': 1,
        'x_port': 1,
        'x_proto': 1,
    }
    DEFAULT_TRANSFORM_GRAPH = '/static-data/DISCO_20181004_sigV30_DARTEL_20181004_reg_x4/graph.yaml'
kind: ConfigMap
metadata:
  name: siibra-spatial-backend
  labels:
    {{- include "hbp_spatial_backend.labels" . | nindent 4 }}
