name: '[tox]'

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Python versions used in BrainVISA base images (i.e. Ubuntu LTS,
        # at the moment 18.04 and 20.04) + the latest stable Python version
        python-version: [ '3.10', '3.8' ]
        os: ['ubuntu-latest']
        include:
        - python-version: '3.6'
          # see https://github.com/actions/setup-python/issues/355#issuecomment-1335042510
          os: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: |
        tox
    # only 3.6 is run with codecov
    - if: ${{ matrix.python-version == '3.6' }}
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
